CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PERSON
(
  ID uuid NOT NULL DEFAULT uuid_generate_v4 (),
  NAME VARCHAR(32) NOT NULL,
  PRESENTTO VARCHAR(32),
  CONSTRAINT PK_PERSON PRIMARY KEY (ID)
);